void increment_CI();
std::string fetch();
void decode(std::string);
void execute(std::string, int);
void display();
void init();
int binToInt(std::string);
std::string intToBin(int);
int convertEndian(std::string num);
int getNumFromAddress(int address);
int findLine(int num);
